name: OCV VS 14 W10

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/OCV-VS-14-W10.yaml'
  workflow_call:

env:
  EXTRA_CMAKE_OPTIONS: '-DBUILD_EXAMPLES=ON -DOPENCV_ENABLE_NONFREE=ON -DCMAKE_BUILD_TYPE=Release'
  OPENCV_TEST_DATA_PATH: ${{ github.workspace }}\opencv_extra\testdata
  PR_AUTHOR: ${{ github.event.pull_request.user.login }}
  PR_AUTHOR_FORK: ${{ github.event.pull_request.head.repo.full_name }}
  SOURCE_BRANCH_NAME: ${{ github.head_ref }}
  TARGET_BRANCH_NAME: ${{ github.base_ref }}
  GTEST_FILTER_STRING: '-Samples.findFile:videoio/videocapture_acceleration.read/122:videoio/videocapture_acceleration.read/126'

jobs:
  vs-16:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
    - name: Setup infra environment
      timeout-minutes: 60
      if: ${{ github.event.repository.name == 'ci-gha-workflow' }}
      shell: bash
      run: echo "TARGET_BRANCH_NAME=4.x" >> $GITHUB_ENV
    - name: PR info
      timeout-minutes: 60
      run: |
        echo "PR Author: ${{ env.PR_AUTHOR }}"
        echo "PR Author fork: ${{ env.PR_AUTHOR_FORK }}"
        echo "Source branch name: ${{ env.SOURCE_BRANCH_NAME }}"
        echo "Target branch name: ${{ env.TARGET_BRANCH_NAME }}"
    - name: Clean
      timeout-minutes: 60
      run: cd ${{ github.workspace }} && rm -rf *
    - name: Fetch opencv
      timeout-minutes: 60
      run: cd ${{ github.workspace }} && git clone --branch ${{ env.TARGET_BRANCH_NAME }} https://github.com/opencv/opencv.git
    - name: Set up Python 3.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.6
        architecture: x64
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
    - name: Configure OpenCV
      timeout-minutes: 60
      run: |
        mkdir ${{ github.workspace }}\build && cd ${{ github.workspace }}\build
        cmake -G ^"Visual Studio 16 2019^" ${{ env.EXTRA_CMAKE_OPTIONS }} ${{ github.workspace }}\opencv
    - name: Build OpenCV
      timeout-minutes: 60
      id: build-opencv
      run: |
        cd ${{ github.workspace }}\build
        cmake --build . --config release --target install

  vs-14:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
    - name: Setup infra environment
      timeout-minutes: 60
      if: ${{ github.event.repository.name == 'ci-gha-workflow' }}
      shell: bash
      run: echo "TARGET_BRANCH_NAME=4.x" >> $GITHUB_ENV
    - name: PR info
      timeout-minutes: 60
      run: |
        echo "PR Author: ${{ env.PR_AUTHOR }}"
        echo "PR Author fork: ${{ env.PR_AUTHOR_FORK }}"
        echo "Source branch name: ${{ env.SOURCE_BRANCH_NAME }}"
        echo "Target branch name: ${{ env.TARGET_BRANCH_NAME }}"
    - name: Clean
      timeout-minutes: 60
      run: cd ${{ github.workspace }} && rm -rf *
    - name: Fetch opencv
      timeout-minutes: 60
      run: cd ${{ github.workspace }} && git clone --branch ${{ env.TARGET_BRANCH_NAME }} https://github.com/opencv/opencv.git
    - name: Set up Python 3.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.6
        architecture: x64
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
    - name: Configure OpenCV
      timeout-minutes: 60
      run: |
        mkdir ${{ github.workspace }}\build && cd ${{ github.workspace }}\build
        cmake -G ^"Visual Studio 14 Win64^" ${{ env.EXTRA_CMAKE_OPTIONS }} ${{ github.workspace }}\opencv
    - name: Build OpenCV
      timeout-minutes: 60
      id: build-opencv
      run: |
        cd ${{ github.workspace }}\build
        cmake --build . --config release --target install
